### ISSUE TITLE
Adjust Makefile

### ISSUE THREAD

**Issue by ghtmtt** [NINAnor/GarminCustomMaps#7]
Makefile is old for QGIS 3 and should be updated. Some issues with `make package `: when the created zip filed is uploaded an error appears:

```
Couldn't load plugin 'GarminCustomMap' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'GarminCustomMaps' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS34~1.1/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/anders/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GarminCustomMap\__init__.py", line 34, in classFactory
    from .GarminCustomMap import GarminCustomMap
  File "C:/PROGRA~1/QGIS34~1.1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/anders/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GarminCustomMap\GarminCustomMap.py", line 46, in 
    from GarminCustomMaps import resources
  File "C:/PROGRA~1/QGIS34~1.1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'GarminCustomMaps'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.1-Madeira Madeira, 383851c597 

Python Path:
C:/PROGRA~1/QGIS34~1.1/apps/qgis/./python
C:/Users/anders/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/anders/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS34~1.1/apps/qgis/./python/plugins
C:\Python27\ArcGIS10.2\Lib\site-packages
C:\Program Files\QGIS 3.4.1\bin\python37.zip
C:\PROGRA~1\QGIS34~1.1\apps\Python37\DLLs
C:\PROGRA~1\QGIS34~1.1\apps\Python37\lib
C:\Program Files\QGIS 3.4.1\bin
C:\PROGRA~1\QGIS34~1.1\apps\Python37
C:\PROGRA~1\QGIS34~1.1\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS34~1.1\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS34~1.1\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS34~1.1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/anders/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by ghtmtt** [comment]
fixed
